### ISSUE TITLE
[Question] Why does it seems ActEditor/spr files doesn't support compression?

### ISSUE THREAD

**Issue by SapitoSucio** [Tokeiburu/ActEditor#3]
Let's take for example the `Å2` sprite from the Sniper's Hawk, which total filesize is 72kb.  I convert the sprite #0 to bgra and extract it, which is 1.92kb, then I upscale it and compress it, the resulting compressed img is 9kb
But after I replace said extracted sprite with the new one, which is compressed, and I save the mob sprite, the .spr file is now 119kb. 

Why does this happen? Is there any way to avoid this without ditching PNGs ?

**Comment by Tokeiburu** [comment]
Spr files don't have support for bgra32 compression. It's a limitation from the file format itself, so there's nothing I can do about it. The image is stored as raw pixel colors.

Though, you do end up having some form of compression via GRF compression (which is usually more than enough anyway). 

I'm using lzma compression, so for `Å2`, here are my results (GRF sizes):
- Original uncompressed size: 72.0kb
- Original compressed size (in a GRF): 24.2kb
- Bgra32 uncompressed size: 541.6kb
- Bgra32 compressed size (in a GRF): 25.9kb

So in the end, it's not like it matters too much? I've tested with higher PNG resolutions and the lzma compression offers very similar sizes (if not better) than their compressed PNG conterparts. Here are a few more examples:
- Uncompressed spr size: 705kb
- Compressed spr size (in a GRF): 408kb
- Original PNG size: 493kb
![t2](https://github.com/Tokeiburu/ActEditor/assets/8761658/b62adbfc-394c-4f69-ba10-3d1cd595b20e)
------
- Lossy compressed PNG file;
- Uncompressed spr size: 705kb
- Compressed spr size (in a GRF): 134kb
- Original PNG size: 140kb
![t3](https://github.com/Tokeiburu/ActEditor/assets/8761658/1be43627-7ed8-4849-aef4-b1c9d32fdabf)
------
Anyway, you shouldn't worry about that since it's irrelevant at the end of the day.
